version: '3'

services:
  app:
    image: lambci/lambda:nodejs12.x
    restart: always
    volumes:
      - ./src:/var/task
    networks:
      - app-net

  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./.data/db:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
